### ISSUE TITLE
Update discord-py to 1.3.1

### ISSUE THREAD

**Issue by benjamin051000** [benjamin051000/Alfred#18]

**Comment by benjamin051000** [comment]
Problems with queueing music when the player is already playing:

```Traceback (most recent call last):
  File "D:\discord_bots\Alfred\venv\lib\site-packages\discord\ext\commands\core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\discord_bots\Alfred\src\music.py", line 165, in play
    await self.playsong(ctx, *query)
  File "D:\discord_bots\Alfred\src\music.py", line 183, in playsong
    await self.joinChannel(ctx, player)
  File "D:\discord_bots\Alfred\src\music.py", line 141, in joinChannel
    log.error('Player already connected.', e)
  File "D:\discord_bots\Alfred\src\logger.py", line 46, in error
    print(' '.join(msg))
TypeError: sequence item 1: expected str instance, ClientException found```
